### ISSUE TITLE
bug report. 

### ISSUE THREAD

**Issue by forfeli** [JohnHeikens/Axo#31]
I was in the air and couldn't move anymore and kept being bent back.

**Comment by JohnHeikens** [comment]
this sounds like you've been glitched out because of a client-server issue. your client couldn't see a certain block you were standing on in the server. relog if it happens again and see if that works.

**Comment by PaxGriefs** [comment]
@forfeli Hello can this Issue be closed? Please reply if we can close this Issue. Thanks :D
