### ISSUE TITLE
Chuckle autobanning people over safe words

### ISSUE THREAD

**Issue by KazumiEF** [JohnHeikens/Axo#57]
When the phrase everything imaginable is said it will auto ban whoever said it. It will even trigger it and "ban" [None] if someone says it in discord
![Capture](https://user-images.githubusercontent.com/69875873/168477757-3fd9c765-f5e1-4f7e-b707-4abcc8f24c95.PNG)
![Capture2](https://user-images.githubusercontent.com/69875873/168477758-9dc23c08-c1a5-43e3-a9e1-70dc4cb3ae13.PNG)
.

**Comment by KazumiEF** [comment]
![Capture3](https://user-images.githubusercontent.com/69875873/168477890-03d623af-6ee7-4214-a293-200ee53b838b.PNG)

**Comment by JohnHeikens** [comment]
thank you so much for reporting! this was caused for hidden n-words in the text. we have updated the filter!
